### ISSUE TITLE
Issue with getting-started-on-gcp-with-terraform

### ISSUE THREAD

**Issue by dominicci** [GoogleCloudPlatform/community#883] opened 2019-05-22 02:14 UTC
Issue Description:

missing key configs for creating firewall rules that will allow ssh into the GCE instance [1]:

// Adding GCP Firewall Rules for MANGEMENT
resource "google_compute_firewall" "allow-mgmt" {
  name    = "allow-mgmt"
  network = "default"

  allow {
    protocol = "icmp"
  }

  allow {
    protocol = "tcp"
    ports    = ["443", "22"]
  }

  source_ranges = ["0.0.0.0/0"]
}

// Adding GCP Firewall Rules for INBOUND
resource "google_compute_firewall" "allow-inbound" {
  name    = "allow-inbound"
  network = "default"

  allow {
    protocol = "tcp"
    ports    = ["80", "22", "221", "222"]
  }

  source_ranges = ["0.0.0.0/0"]
}

// Adding GCP Firewall Rules for OUTBOUND
resource "google_compute_firewall" "web-allow-outbound" {
  name    = "web-allow-outbound"
  network = "default"

  allow {
    protocol = "all"
  }

  source_ranges = ["0.0.0.0/0"]
}

// Adding GCP Firewall Rules for OUTBOUND
resource "google_compute_firewall" "db-allow-outbound" {
  name    = "db-allow-outbound"
  network = "default"

  allow {
    protocol = "all"
  }

  source_ranges = ["0.0.0.0/0"]
}

[1] https://github.com/PaloAltoNetworks/GCP-Terraform-Samples/blob/master/Two-Tier/Main.tf

**Comment by ToddKopriva** [comment] 2019-05-22 05:27
@chrisst , could you take a look at this issue regarding a tutorial that you submitted?

**Comment by chrisst** [comment] 2019-05-23 20:54
I just tested this again and it looks like a brand new GCP project will be created with a default firewall rule that allows ssh:
![Screen Shot 2019-05-23 at 1 41 05 PM](https://user-images.githubusercontent.com/1569002/58284884-77b20a80-7d60-11e9-8b20-30ea503268cf.png)
Additionally some of the other proposed firewalls above allow way more access to the instance than is required for this tutorial. I'm not particularly comfortable encouraging people to add such wide open firewall policies in a tutorial.

@dominicci if there is an issue with the tutorial can you post more details of what you are encountering?

**Comment by dominicci** [comment] 2019-05-23 22:20
Fair enough.

Maybe you could modify it for existing projects. My request to ssh kept
timing out because the plan doesn't execute the required firewall rules. Or
maybe I'm missing something.

**Comment by chrisst** [comment] 2019-05-24 17:10
The firewalls do take a little while to get created. If you have freshly created a project there a number of 'initialization' steps that happen which can take several minutes and one of those steps is creating the default firewall rules. I'm not an expert on how projects are initialized but this is my experience so far. 

I would check the 'firewalls' section in the UI and see if the default rules are there by now. 

In the mean time, I'll add some caveats to wait for a new project to finish initializing before some of the workflow can be completed.

**Comment by ToddKopriva** [comment] 2019-05-24 18:14
Because it seems that there is not a bug in the tutorial, I'm going to close this issue.

Chris, if you want to create a pull request to add the caveats that you mentioned, I'll work with you to get it reviewed and merged.

@dominicci , thanks for alerting to us to the potential issue and helping us to see the need for some improvements in this area.

**Closed by ToddKopriva** 2019-05-24 18:14 UTC
Labels: bug
