### ISSUE TITLE
Issue with tutorials/run-wordpress-on-appengine-standard/index.md

### ISSUE THREAD

**Issue by marcucio** [GoogleCloudPlatform/community#1131] opened 2020-01-22 12:21 UTC
"Enable the Google Cloud Storage plugin" part does not work correctly. After setting permissions and enabling the plugin, when I try to upload I get the following error:

Fatal error: Uncaught GuzzleHttp\Exception\ClientException: Client error: `GET https://www.googleapis.com/storage/v1/b/appnamexxx.appspot.com/o/1%2F2020%2F01` resulted in a `404 Not Found` response: { "error": { "code": 404, "message": "No such object: appnamexxx.appspot.com/1/2020/01", "errors": [ (truncated...) in /srv/wp-content/plugins/gcs/vendor/guzzlehttp/guzzle/src/Exception/RequestException.php:113

**Comment by ToddKopriva** [comment] 2020-01-22 17:56
@bshaffer , could you have a look at this issue report about a tutorial that you wrote?

**Comment by ToddKopriva** [comment] 2020-01-22 17:57
@marcucio , thanks for the report.

**Comment by tjwebb** [comment] 2020-01-22 19:43
@marcucio make sure you're using the PROJECT ID, not the name of your app engine application.

**Comment by tjwebb** [comment] 2020-01-22 19:46
@marcucio it appears to be a bug with the WP plugin. see https://wordpress.org/support/topic/fatal-error-uncaught-guzzlehttpexceptionclientexception/. Downgrading the plugin to the previous version may help.

**Comment by marcucio** [comment] 2020-01-30 16:58
Downgrading plugin to previous version didn't work for me, is this being actively worked on or should I attempt to debug the issue further?

**Comment by bshaffer** [comment] 2020-02-01 00:22
Thank you everyone, this issue should now be fixed. If you are able to, update to `1.5.1` and try again.

@marcucio if you are still receiving that error, it may have to do with your wordpress version or theme. I updated with a fresh install and it worked. Another thing you can try is to update the `wp-content/plugins/gcs` vendor directory by doing the following:

```sh
$ cd wp-content/plugins/gcs
$ rm -rf vendor
$ composer require google/cloud-storage --update-no-dev
```

This will install the latest version of the Cloud Storage client library, which might have a bug fix for your issue.

**Comment by marcucio** [comment] 2020-02-01 01:57
Did you verify on App Engine or just locally? On app engine I get the following error. I'm going to do a fresh install install of wordpress to verify nothing is corrupted.

`
Warning: stat(): stat failed for gs://tigerishmom.appspot.com/1/2020/01 in /srv/wp-admin/includes/file.php on line 890 Warning: chmod(): Google\Cloud\Storage\StreamWrapper::stream_metadata is not implemented! in /srv/wp-admin/includes/file.php on line 892 Warning: stat(): stat failed for gs://tigerishmom.appspot.com/1/2020/01 in /srv/wp-includes/class-wp-image-editor-gd.php on line 445 Warning: chmod(): Google\Cloud\Storage\StreamWrapper::stream_metadata is not implemented! in /srv/wp-includes/class-wp-image-editor-gd.php on line 447 Warning: stat(): stat failed for gs://tigerishmom.appspot.com/1/2020/01 in /srv/wp-includes/class-wp-image-editor-gd.php on line 445 Warning: chmod(): Google\Cloud\Storage\StreamWrapper::stream_metadata is not implemented! in /srv/wp-includes/class-wp-image-editor-gd.php on line 447 Warning: stat(): stat failed for gs://tigerishmom.appspot.com/1/2020/01 in /srv/wp-includes/class-wp-image-editor-gd.php on line 445 Warning: chmod(): Google\Cloud\Storage\StreamWrapper::stream_metadata is not implemented! in /srv/wp-includes/class-wp-image-editor-gd.php on line 447 Warning: stat(): stat failed for gs://tigerishmom.appspot.com/1/2020/01 in /srv/wp-includes/class-wp-image-editor-gd.php on line 445 Warning: chmod(): Google\Cloud\Storage\StreamWrapper::stream_metadata is not implemented! in /srv/wp-includes/class-wp-image-editor-gd.php on line 447 Warning: stat(): stat failed for gs://tigerishmom.appspot.com/1/2020/01 in /srv/wp-includes/class-wp-image-editor-gd.php on line 445 Warning: chmod(): Google\Cloud\Storage\StreamWrapper::stream_metadata is not implemented! in /srv/wp-includes/class-wp-image-editor-gd.php on line 447 135
`

**Comment by marcucio** [comment] 2020-02-01 02:42
fresh install seems to work, thanks for all your help and quick response!

**Comment by ToddKopriva** [comment] 2020-02-03 16:02
@marcucio , I'm going to close this issue report, since it seems that the issue is resolved for you now.

Feel free to re-open the issue report if necessary.

**Closed by ToddKopriva** 2020-02-03 16:02 UTC
Labels: bug
