### ISSUE TITLE
Issue with kotlin-springboot-container-engine

### ISSUE THREAD

**Issue by pupeno** [GoogleCloudPlatform/community#1009] opened 2019-08-29 18:26 UTC
On this step:

> Go to the API Library in the Cloud Console. Use it to enable the following APIs:
> -    Google Cloud Container Builder API
> -    Google Container Engine API

I couldn't figure out what those two thing are nor find them on the linked page.

**Comment by ToddKopriva** [comment] 2019-08-29 18:34
Thanks for the report. I'll have a look.

**Comment by ToddKopriva** [comment] 2019-09-04 21:57
When I go to the API Library page and do a search like this:
http://console.cloud.google.com/apis/library?&q=container

... I see the the Google Container Engine API as the first result and the Google Cloud Container Builder API entry about sixth on the list of results.

Does that help?

**Comment by ToddKopriva** [comment] 2019-09-06 20:15
I'm going to close this issue, since I think that you have he information that you need. Feel free to re-open this issue if needed.

**Comment by pupeno** [comment] 2019-09-24 10:00
This is what I see, which doesn't include Google Cloud Container Builder:

![Annotation 2019-09-24 110008](https://user-images.githubusercontent.com/8425/65502362-8ea56c80-deba-11e9-9291-0f09f168e99d.png)

**Comment by ToddKopriva** [comment] 2019-09-24 17:07
Ah, thanks for that. And thanks for your patience.

I see what the problem is now.

I'm going to switch this issue from being a question to a bug, since you are correct that this shows a problem with the document.

**Comment by pupeno** [comment] 2019-09-24 17:17
No problem! I'm sorry it took me so long to respond, I was crazy busy.

**Comment by ToddKopriva** [comment] 2021-08-02 18:15
closing because the outdated tutorial has been archived

**Closed by ToddKopriva** 2021-08-02 18:15 UTC
Labels: bug
