### ISSUE TITLE
petclinic on GAE

### ISSUE THREAD

**Issue by ramimmadi** [GoogleCloudPlatform/community#268] opened 2017-10-16 10:46 UTC
_https://cloud.google.com/community/tutorials/run-spring-petclinic-on-app-engine-cloudsql_ I am trying to deploy petclinic using the above url. did all the mnetioned steps but still facing sql related errors.. "Unknow syntax DATABASE." please help me out.

**Comment by jabubake** [comment] 2017-10-23 16:01
duplicate of #271

**Closed by jabubake** 2017-10-23 16:01 UTC
Labels: question
