### ISSUE TITLE
Tutorial run-expressjs-on-google-app-engine doesn't work

### ISSUE THREAD

**Issue by Nearoo** [GoogleCloudPlatform/community#920] opened 2019-06-18 11:09 UTC
Fails in the cloud with

    Error: Cannot find module 'express'

**Comment by Nearoo** [comment] 2019-06-18 11:13
[Link to Tutorial](https://cloud.google.com/community/tutorials/run-expressjs-on-google-app-engine)

**Comment by ToddKopriva** [comment] 2019-06-18 14:15
Thanks for the report.

**Comment by tjwebb** [comment] 2020-01-09 20:37
I was not able to reproduce this issue

**Comment by ToddKopriva** [comment] 2020-01-09 20:53
Thanks, Travis.

I'm going to close this issue report for now.

Silas, if you need help, I recommend bringing your issue to one of the forums described here:
https://cloud.google.com/support/docs/community

Many members of the GCP community---including Google employees and other experts---help out on those forums.

If you are certain that there is a problem with this tutorial, and you can give more detailed information about how to reproduce the problem, please re-open this issue report and let us know.

**Closed by ToddKopriva** 2020-01-09 20:53 UTC
Labels: bug
