### ISSUE TITLE
Issue with tutorials/managing-gcp-projects-with-terraform/index.md

### ISSUE THREAD

**Issue by priyankak1212** [GoogleCloudPlatform/community#1387] opened 2020-08-06 09:52 UTC
Hi,
I need to create new GCP project using organisation id.For that which json key need to be used??? Is that first we have to create service account for new project?

**Comment by ToddKopriva** [comment] 2020-08-06 15:06
closing as a duplicate of this issue report:
https://github.com/GoogleCloudPlatform/community/issues/1388

**Closed by ToddKopriva** 2020-08-06 15:06 UTC
