### ISSUE TITLE
Tutorial Request

### ISSUE THREAD

**Issue by tenebreux** [GoogleCloudPlatform/community#1503] opened 2020-11-03 18:10 UTC
Dear lovely people,

Is it possible to get someone to create a tutorial that would be executed from an OSX terminal window that would work for a tutorial like this one: "Run WordPress on App Engine standard environment" ::: https://cloud.google.com/community/tutorials/run-wordpress-on-appengine-standard 

I get stuck on the line where the tutorial runs composer. composer isn't available on a mac. everything else works till there.

**Comment by ToddKopriva** [comment] 2020-12-31 03:39
closing as a duplicate of this:
https://github.com/GoogleCloudPlatform/community/issues/1504

**Closed by ToddKopriva** 2020-12-31 03:39 UTC
Labels: enhancement (tutorial request)
