### ISSUE TITLE
Issue with tutorials/dlp-to-datacatalog-tags/

### ISSUE THREAD

**Issue by akspow** [GoogleCloudPlatform/community#1345] opened 2020-07-11 15:41 UTC
0 tables are inspected even though I have configured the correct project-id, dataset, and table. I am using Bigquery as database type.

**Comment by ToddKopriva** [comment] 2020-07-11 20:52
@mesmacosta , could you have a look at this issue reported about a tutorial that you submitted?

**Comment by mesmacosta** [comment] 2020-07-12 17:44
@askpow could you provide more information about your execution?

- The command line args
- The execution log
- The roles assigned to the service account you executed.

Please anonymize your project, and dataset info.

**Comment by mesmacosta** [comment] 2020-07-12 17:46
Also, if you could turn the debug flag on, for additional logging to help us troubleshoot it:

https://github.com/GoogleCloudPlatform/community/blob/master/tutorials/dlp-to-datacatalog-tags/src/main/java/com/example/dlp/DlpDataCatalogTagsTutorial.java#L74

**Comment by akspow** [comment] 2020-07-15 12:25
Hi @mesmacosta,
Sorry for the late reply.
So surprisingly, when I cleaned and recompiled the java package that error went away.
But I am experiencing a new error here.
Tried to trace out the cause but couldn't find out.
I have turned the debug flag on.
Here is the error log.
-----------------------------------------
>[Start: Wed Jul 15 05:00:31 PDT 2020]
Inspect SQL via JDBC V0.1
jdbc:bigquery://https://www.googleapis.com/bigquery/v2:443;OAuthType=3;ProjectId=project-id;
 Start Run ID: xx

>Runnable started for: table1 on thread: pool-3-thread-1
|
> DLP infoType Profile: [dataset-id][table1]>> Runnable started for: table2 on thread: pool-3-thread-3
|
> DLP infoType Profile: [dataset-id][table2]>> Runnable started for: table3 on thread: pool-3-thread-2
|
> DLP infoType Profile: [dataset-id][table3]>> Runnable started for: table4 on thread: pool-3-thread-4
|
> DLP infoType Profile: [dataset-id][table4]..(Inspecting Data)...(Inspecting Data)...(Inspecting Data)...(Inspecting Data).
|
[ Request Size (dataset-id:table1): request#1 | start-row=500 | row-count=500 | cell-count=4000]
java.lang.IllegalStateException
        at com.google.common.base.Preconditions.checkState(Preconditions.java:495)
        at com.google.api.client.util.Preconditions.checkState(Preconditions.java:79)
        at com.google.api.client.googleapis.batch.BatchRequest.execute(BatchRequest.java:217)
        at com.example.dlp.DlpDataCatalogTagsTutorial.writeFindingsToDataCatalog(DlpDataCatalogTagsTutorial.java:780)
        at com.example.dlp.DlpDataCatalogTagsTutorial.lambda$processTable$1(DlpDataCatalogTagsTutorial.java:413)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:834)
>> Runnable done for: table1 on thread: pool-3-thread-3
|
[ Request Size (dataset-id:table2): request#1 | start-row=500 | row-count=500 | cell-count=4000]
java.lang.IllegalStateException
        at com.google.common.base.Preconditions.checkState(Preconditions.java:495)
        at com.google.api.client.util.Preconditions.checkState(Preconditions.java:79)
        at com.google.api.client.googleapis.batch.BatchRequest.execute(BatchRequest.java:217)
        at com.example.dlp.DlpDataCatalogTagsTutorial.writeFindingsToDataCatalog(DlpDataCatalogTagsTutorial.java:780)
        at com.example.dlp.DlpDataCatalogTagsTutorial.lambda$processTable$1(DlpDataCatalogTagsTutorial.java:413)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:834)
>> Runnable done for: table2 on thread: pool-3-thread-2
|
[ Request Size (dataset-id:table3): request#1 | start-row=500 | row-count=500 | cell-count=9000]
java.lang.IllegalStateException
        at com.google.common.base.Preconditions.checkState(Preconditions.java:495)
        at com.google.api.client.util.Preconditions.checkState(Preconditions.java:79)
        at com.google.api.client.googleapis.batch.BatchRequest.execute(BatchRequest.java:217)
        at com.example.dlp.DlpDataCatalogTagsTutorial.writeFindingsToDataCatalog(DlpDataCatalogTagsTutorial.java:780)
        at com.example.dlp.DlpDataCatalogTagsTutorial.lambda$processTable$1(DlpDataCatalogTagsTutorial.java:413)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:834)
>> Runnable done for: table3 on thread: pool-3-thread-1
|
[ Request Size (dataset-id:table4): request#1 | start-row=500 | row-count=500 | cell-count=5000]
java.lang.IllegalStateException
        at com.google.common.base.Preconditions.checkState(Preconditions.java:495)
        at com.google.api.client.util.Preconditions.checkState(Preconditions.java:79)
        at com.google.api.client.googleapis.batch.BatchRequest.execute(BatchRequest.java:217)
        at com.example.dlp.DlpDataCatalogTagsTutorial.writeFindingsToDataCatalog(DlpDataCatalogTagsTutorial.java:780)
        at com.example.dlp.DlpDataCatalogTagsTutorial.lambda$processTable$1(DlpDataCatalogTagsTutorial.java:413)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:834)
>> Runnable done for: table4 on thread: pool-3-thread-4
 4 tables inspected
 End Run ID: xxx
[End: Wed Jul 15 05:00:42 PDT 2020]
[Duration:   0 days,   0 hours,   0 minutes,   11 seconds.]
-----------------------------------------

**Comment by mesmacosta** [comment] 2020-07-15 18:24
Hi @akspow 
- Can you also provide the command line args? 
- How many threads did you use?
- Could you try running with just one thread? So I can narrow down the issue.

Please anonymize your project, and dataset info.

**Comment by akspow** [comment] 2020-07-15 18:54
Hi @mesmacosta 
Command line args i used:

>java -cp target/dlp-to-datacatalog-tags-0.1-jar-with-dependencies.jar com.example.dlp.DlpDataCatalogTagsTutorial \\
-dbType "bigquery" \\
-limitMax 500\\
-dbName dbname\\
-projectId project-id\\
-threadPoolSize 5 \\
-inspectTemplate "path to template"\\
-minThreshold 100

I was initially using 5 threads
Tried with 1 thread. still having the same issue.

Thanks :)

**Comment by mesmacosta** [comment] 2020-07-15 19:06
- inspectTemplate

What infoTypes did you set up?

**Comment by mesmacosta** [comment] 2020-07-15 19:16
Could you try running with the sample data from this tutorial:
https://github.com/mesmacosta/dlp-to-datacatalog-tags-tutorial/blob/master/TUTORIAL.md

And let me know if it works for you?

Trying to narrow down if it could be something with:
- The service account roles you are using.
- The Inspect template info types.
- The data from the Big Query tables being inspected.

Understanding this issue, will help improve this script by adding better error messages to it, so it's easier for user to troubleshoot it.

**Comment by akspow** [comment] 2020-07-15 21:14
Okay, so the tutorial works perfectly.
In my case, I was using ["EMAIL_ADDRESS","PHONE_NUMBER","US_SOCIAL_SECURITY_NUMBER"] as infotypes.
Tried the tutorial template with my dataset too. Still having the same issue.
Most probably it has something to do with my Bigquery table data.

**Comment by mesmacosta** [comment] 2020-07-15 21:35
Hi @akspow,

- Is there anything different about your BigQuery table data?
- Are you using STRUCT (or RECORD ) types?
- By any chance could you provide some sample fake/anonymized data that I could simulate your issue?

Thanks

**Comment by akspow** [comment] 2020-07-16 06:45
Hi,
I'm not using any STRUCT/RECORD type fields.
I'm using a fake employee dataset too.
I'm sharing with you the CSV files zipped.
[employee_sample.zip](https://github.com/GoogleCloudPlatform/community/files/4929752/employee_sample.zip)


data.

**Comment by mesmacosta** [comment] 2020-07-16 14:59
Thanks, I will try to reproduce it and troubleshoot the issue.

**Comment by akspow** [comment] 2020-07-16 16:01
Thanks @mesmacosta for your time :)

**Comment by mesmacosta** [comment] 2020-07-16 18:16
Hi @akspow 

Just ran successfully with your data, using 5 threads:

```
Inspect SQL via JDBC V0.1
jdbc:bigquery://https://www.googleapis.com/bigquery/v2:443;OAuthType=3;ProjectId=my-project;
-----------------------------------------
 Start Run ID: 15127c0e-ae53-45aa-a563-d4b0e56bac11
-----------------------------------------
>> Runnable started for: employee_sample on thread: pool-3-thread-1
|
> DLP infoType Profile: [dlp_error_test][employee_sample]>> Runnable started for: employee_test on thread: pool-3-thread-2
|
> DLP infoType Profile: [dlp_error_test][employee_test]..(Inspecting Data)...(Inspecting Data).|
[ Request Size (dlp_error_test:employee_test): request#1 | start-row=1000 | row-count=1000 | cell-count=8000]
>> Column [last_name] has findings
>> Column [first_name] has findings
[CacheMiss] - getTagTemplate
[CacheMiss] - lookupEntry
|
[ Request Size (dlp_error_test:employee_sample): request#1 | start-row=1000 | row-count=1000 | cell-count=18000]
>> Column [last_name] has findings
[CacheHit] - getTagTemplate
[CacheMiss] - listTags
[CacheMiss] - lookupEntry
[CacheMiss] - listTags
>> Column [email] has findings
[CacheHit] - getTagTemplate
[CacheHit] - lookupEntry
[CacheHit] - listTags
>> Column [phone_number] has findings
[Created]
>> Runnable done for: employee_test on thread: pool-3-thread-2
[CacheMiss] - getTagTemplate
[CacheHit] - lookupEntry
[CacheHit] - listTags
>> Column [first_name] has findings
[CacheHit] - getTagTemplate
[CacheHit] - lookupEntry
[CacheHit] - listTags
[Created]
[Created]
[Created]
[Created]
>> Runnable done for: employee_sample on thread: pool-3-thread-1

-----------------------------------------
 2 tables inspected
 End Run ID: 15127c0e-ae53-45aa-a563-d4b0e56bac11
-----------------------------------------
```
Tags created:
![employee_test](https://user-images.githubusercontent.com/3176836/87707246-31dfaf00-c777-11ea-800f-a1270469736f.png)
![employee_sample](https://user-images.githubusercontent.com/3176836/87707254-34da9f80-c777-11ea-85ae-5de4ed9da167.png)

Could you try running on Cloud Shell? To see if it's related to the environment you are executing.

**Comment by akspow** [comment] 2020-07-17 06:08
I am actually running on Cloud shell

**Comment by mesmacosta** [comment] 2020-07-17 17:18
I see. 

I'm unable to reproduce the error using the test data. Can you provide a reproducible scenario?

**Comment by akspow** [comment] 2020-07-22 08:01
Hi @mesmacosta 
Ok, so what I've learned is that it throws an error for certain data.
I've tried with 5 different data files
3 of them worked
2 throws the error(100_c and sample-data)
Could you tell me why this happens when data varies?
[dataset.zip](https://github.com/GoogleCloudPlatform/community/files/4958654/dataset.zip)

**Comment by mesmacosta** [comment] 2020-07-22 14:34
Hi @akspow 

The issue was unrelated with the data, but with the following corner case:

-> When a Table had DLP findings and all findings were below the minimum threshold set at runtime.

I sent this PR with the fix: https://github.com/GoogleCloudPlatform/community/pull/1366

If you want to test without the fix, just decrease the `-minThreshold` to 1

**Comment by akspow** [comment] 2020-07-22 14:57
Thank you @mesmacosta for your time!

**Closed** 2020-07-22 14:58 UTC
Labels: bug
