### ISSUE TITLE
How to update the laravel app in google app engine?

### ISSUE THREAD

**Issue by tjnapster555** [GoogleCloudPlatform/community#273] opened 2017-10-17 18:59 UTC
I am able to do a first deploy of laravel on google app engine but in tutorial its not mention that how to deploy the update that we make in laravel files like if i make a new controller how to deploy that.
because when ever i do this gcloud app deploy it upload the whole application and recreate the laravel app this is not good

**Comment by bshaffer** [comment] 2017-10-23 20:30
Hi @tjnapster555 ! You are correct, in order to update you just run `gcloud app deploy` again. 

App Engine is ephemeral, and so it *should* "recreate the laravel app". This is the expected behavior. As long as you're using CloudSQL in the backend, and storing files to Google Cloud Storage, replacing the running application code will not have any negative affect.

**Comment by tjnapster555** [comment] 2017-11-05 14:05
@bshaffer can you make a tutorial using standard app engine or computer engine because flex use too much sources for laravel end i just made a hello world app its using 2 gb ram just to run laravel hello world this is not good make a tutorial using computer engine or app engine with standard 
also add the support of npm for laravel echo

**Comment by bshaffer** [comment] 2017-11-06 19:48
@tjnapster555 I agree this is a good idea, particularly for Compute Engine since App Engine Standard is currently for php55 only.

**Comment by flashadvocate** [comment] 2018-08-03 13:56
@bshaffer this will very soon change as GAE will be moving to PHP72

**Closed** 2019-01-02 18:52 UTC
Labels: question

**Comment by bshaffer** [comment] 2019-01-02 20:35
The new sample is available at https://github.com/GoogleCloudPlatform/php-docs-samples/tree/master/appengine/php72/laravel-framework

**Comment by ToddKopriva** [comment] 2019-01-02 21:06
Thanks, Brent.
