### ISSUE TITLE
Issue with managing-gcp-projects-with-terraform

### ISSUE THREAD

**Issue by dsmithuk** [GoogleCloudPlatform/community#456] opened 2018-06-13 15:11 UTC
admin_@cloudshell:~ (davecloud-globalservices)$ gcloud service-management enable cloudresourcemanager.googleapis.com
ERROR: (gcloud.service-management.enable) The `service-management enable` command has been replaced by `services enable`.
admin_@cloudshell:~ (davecloud-globalservices)$ gcloud service-management enable cloudbilling.googleapis.com
ERROR: (gcloud.service-management.enable) The `service-management enable` command has been replaced by `services enable`.
admin_@cloudshell:~ (davecloud-globalservices)$ gcloud service-management enable iam.googleapis.com
ERROR: (gcloud.service-management.enable) The `service-management enable` command has been replaced by `services enable`.
admin_@cloudshell:~ (davecloud-globalservices)$ gcloud service-management enable compute.googleapis.com
ERROR: (gcloud.service-management.enable) The `service-management enable` command has been replaced by `services enable`.
admin_@cloudshell:~ (davecloud-globalservices)$
admin_@cloudshell:~ (davecloud-globalservices)$ gcloud organizations add-iam-policy-binding ${TF_VAR_org_id} \
>   --member serviceAccount:global-terraform@${TF_ADMIN}.iam.gserviceaccount.com \
>   --role roles/resourcemanager.projectCreator

**Comment by jlucktay** [comment] 2018-07-24 10:56
This issue looks like a duplicate of #448

**Comment by ToddKopriva** [comment] 2019-01-02 22:01
closing as duplicate

**Closed by ToddKopriva** 2019-01-02 22:01 UTC
